### PR TITLE
fix: makes windows builds work

### PR DESCRIPTION
**Pull request by kobigurk**

### CODE REVIEW

**Comment by bowd** [comment]
I think we should also remove the `-lunwind` from https://github.com/celo-org/celo-bls-go/blob/master/bls/bls_windows.go

**Comment by kobigurk** [comment]
> I think we should also remove the `-lunwind` from https://github.com/celo-org/celo-bls-go/blob/master/bls/bls_windows.go

You're right, done!

**Comment by bowd** [comment]
After trying this branch out we figured out that `libunwind` is actually still required when compiling for window 386 and linking the `386` lib but it's not required when compiling for `amd64`. 

So unless we can change anything else in how the rust lib is built to remove the dependency on `libunwind`, I think it's best to add `-lunwind` back to https://github.com/celo-org/celo-bls-go/blob/master/bls/bls_windows.go to keep things explicit.

**Review by gakonst — COMMENTED** [review]
Changes are straightforward, so ACK from me if it ends up working on windows

**Comment by kobigurk** [comment]
@bowd apparently it's not libunwind that's needed, it's a Rust cross-compilation issue: https://github.com/rust-lang/rust/issues/47493

It might just get fixed at some later version, or we could use the workaround they mentioned there. In any case, we don't really want to support i686, so I think we can leave it as is.

**Review by gakonst — APPROVED** [review]

**Pull request merged**
